#@ def labels():
app: antrea
#@ end

#@ def metadata(name):
labels: #@ labels()
name: #@ name
#@ end

#! todo(knabben) - overlay testing with webhooks.rules[0].operations = UPDATE

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata: #@ metadata("crdmutator.antrea.io")
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: antrea
        namespace: kube-system
        path: /mutate/acnp
    name: acnpmutator.antrea.io
    rules:
      - apiGroups:
          - crd.antrea.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusternetworkpolicies
        scope: Cluster
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: antrea
        namespace: kube-system
        path: /mutate/anp
    name: anpmutator.antrea.io
    rules:
      - apiGroups:
          - crd.antrea.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - networkpolicies
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata: #@ metadata("crdmutator.antrea.tanzu.vmware.com")
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: antrea
        namespace: kube-system
        path: /mutate/acnp
    name: acnpmutator.antrea.tanzu.vmware.com
    rules:
      - apiGroups:
          - security.antrea.tanzu.vmware.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusternetworkpolicies
        scope: Cluster
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: antrea
        namespace: kube-system
        path: /mutate/anp
    name: anpmutator.antrea.tanzu.vmware.com
    rules:
      - apiGroups:
          - security.antrea.tanzu.vmware.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - networkpolicies
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata: #@ metadata("crdvalidator.antrea.io")
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: antrea
        namespace: kube-system
        path: /validate/tier
    name: tiervalidator.antrea.io
    rules:
      - apiGroups:
          - crd.antrea.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - tiers
        scope: Cluster
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: antrea
        namespace: kube-system
        path: /validate/acnp
    name: acnpvalidator.antrea.io
    rules:
      - apiGroups:
          - crd.antrea.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusternetworkpolicies
        scope: Cluster
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: antrea
        namespace: kube-system
        path: /validate/anp
    name: anpvalidator.antrea.io
    rules:
      - apiGroups:
          - crd.antrea.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - networkpolicies
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: antrea
        namespace: kube-system
        path: /validate/clustergroup
    name: clustergroupvalidator.antrea.io
    rules:
      - apiGroups:
          - crd.antrea.io
        apiVersions:
          - v1alpha3
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - clustergroups
        scope: Cluster
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: antrea
        namespace: kube-system
        path: /validate/externalippool
    name: externalippoolvalidator.antrea.io
    rules:
      - apiGroups:
          - crd.antrea.io
        apiVersions:
          - v1alpha2
        operations:
          - UPDATE
        resources:
          - externalippools
        scope: Cluster
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: antrea
        namespace: kube-system
        path: /validate/egress
    name: egressvalidator.antrea.io
    rules:
      - apiGroups:
          - crd.antrea.io
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
        resources:
          - egresses
        scope: Cluster
    sideEffects: None
    timeoutSeconds: 5
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata: #@ metadata("crdvalidator.antrea.tanzu.vmware.com")
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: antrea
        namespace: kube-system
        path: /validate/tier
    name: tiervalidator.antrea.tanzu.vmware.com
    rules:
      - apiGroups:
          - security.antrea.tanzu.vmware.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - tiers
        scope: Cluster
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: antrea
        namespace: kube-system
        path: /validate/acnp
    name: acnpvalidator.antrea.tanzu.vmware.com
    rules:
      - apiGroups:
          - security.antrea.tanzu.vmware.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusternetworkpolicies
        scope: Cluster
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: antrea
        namespace: kube-system
        path: /validate/anp
    name: anpvalidator.antrea.tanzu.vmware.com
    rules:
      - apiGroups:
          - security.antrea.tanzu.vmware.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - networkpolicies
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 5
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: antrea
        namespace: kube-system
        path: /validate/clustergroup
    name: clustergroupvalidator.antrea.tanzu.vmware.com
    rules:
      - apiGroups:
          - core.antrea.tanzu.vmware.com
        apiVersions:
          - v1alpha2
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - clustergroups
        scope: Cluster
    sideEffects: None
    timeoutSeconds: 5
